*error_aggregateTwoErrors.js:*
throw aggregateTwoErrors(err, originalError);
^
AggregateError: original
    at Object.<anonymous> (*test*message*error_aggregateTwoErrors.js:*:*)
    at Module._compile (node:internal/modules/cjs/loader:*:*)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:*:*)
    at Module.load (node:internal/modules/cjs/loader:*:*)
    at Function.Module._load (node:internal/modules/cjs/loader:*:*)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:*:*)
    at node:internal/main/run_main_module:*:* {
  code: 'ERR0',
  [errors]: [
    Error: original
        at Object.<anonymous> (*test*message*error_aggregateTwoErrors.js:*:*)
        at Module._compile (node:internal/modules/cjs/loader:*:*)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:*:*)
        at Module.load (node:internal/modules/cjs/loader:*:*)
        at Function.Module._load (node:internal/modules/cjs/loader:*:*)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:*:*)
        at node:internal/main/run_main_module:*:* {
      code: 'ERR0'
    },
    Error: second error
        at Object.<anonymous> (*test*message*error_aggregateTwoErrors.js:*:*)
        at Module._compile (node:internal/modules/cjs/loader:*:*)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:*:*)
        at Module.load (node:internal/modules/cjs/loader:*:*)
        at Function.Module._load (node:internal/modules/cjs/loader:*:*)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:*:*)
        at node:internal/main/run_main_module:*:* {
      code: 'ERR1'
    }
  ]
}
